#!/usr/bin/env node
const debug = require('debug')('law-portal');
const app = require('../server');


app.set('port', process.env.PORT || 3009);

const server = app.listen(app.get('port'), function () {
    debug('Express server listening on port ' + server.address().port);
    console.log('Сервер работает и доступен по адресу http://localhost:'+app.get('port'));
});
